apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot-app
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: my-springboot-app
        image: 992382630793.dkr.ecr.ap-south-1.amazonaws.com/nagp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
  name: springboot-app
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /index.html
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: NodePort
  selector:
    app: springboot-app
